import type { ChoiceData, SceneData } from "./scenario.js";

/** Stage 5's single linked area: an evidence hub, three investigation tracks,
 * an irreversible hearing, and a changed return to Lowsail. */
export const LANTERN_SCENES = [
  {
    id: "lantern-landing",
    title: "Lantern Archive Landing",
    text: [
      {
        text: "The Lantern Archive stands above the canal in a house of blue glass. Archivist Sera Vale notices a faded counterseal above Tovan's local mark on the stolen order. She needs two independent pieces of evidence to call a hearing against the upstream authority, Prefect Oren Vask.",
      },
      {
        text: "Nessa's shared repair gives the order a maintenance trail that can be checked.",
        when: [{ type: "flag", flag: "shared-water", value: true }],
      },
      {
        text: "Tovan's ration valve carries the official authorization that Oren Vask wants to keep in force.",
        when: [{ type: "flag", flag: "council-control", value: true }],
      },
      {
        text: "Bram's family manifest makes the diversion's human cost impossible to file as a mere clerical error.",
        when: [{ type: "flag", flag: "evacuation-plan", value: true }],
      },
    ],
  },
  {
    id: "archive-hall",
    title: "Lantern Archive Hall",
    text: [
      {
        text: "Sera Vale lays the stolen order under a glass weight. Jalen Rook knows where the night ledger is kept; the seal workroom can trace the hand that authorized the diversion; Mara Venn is hidden below the stacks.",
      },
      {
        text: "You have enough separate evidence to call a hearing, but the choice of whose safety to spend will be final.",
        when: [{ type: "resourceAtLeast", resource: "archive-evidence", value: 2 }],
      },
      {
        text: "Nessa's repair log is the cleanest way into the ledger. It also gives Mara a reason to believe the Archive will protect her.",
        when: [{ type: "flag", flag: "shared-water", value: true }],
      },
      {
        text: "Your council seal opens the official file. In return for your cooperation, Sera will assume one of your outstanding obligations. You keep the seal as a custody receipt.",
        when: [{ type: "flag", flag: "council-control", value: true }, { type: "flag", flag: "council-seal", value: true }],
      },
      {
        text: "Mara knows you installed the council's ration rule and refuses an informal deposition. A professional guarantee can earn her trust; a council summons will compel her at the cost of another debt, with her name unprotected.",
        when: [{ type: "flag", flag: "council-control", value: true }, { type: "flag", flag: "archive-witness-contacted", value: false }],
      },
      {
        text: "Bram's family manifest gives the case a public face. Mara can be sheltered with the families even if she never signs a deposition.",
        when: [{ type: "flag", flag: "evacuation-plan", value: true }],
      },
    ],
  },
  {
    id: "diversion-ledger-room",
    title: "Night Ledger Room",
    text: [
      {
        text: "Jalen Rook keeps the night ledger behind a loose lantern panel. He moved Vask's copy after dark and will open the panel only if Sera promises that his name will not be the first one entered in the record.",
      },
      {
        text: "The ledger records a night transfer from Lowsail's intake to Vask's private mill branch. It establishes who benefited, but Vask can still claim the transfer was an emergency measure.",
      },
    ],
  },
  {
    id: "seal-workroom",
    title: "Seal Workroom",
    text: [
      {
        text: "A sealwright's bench holds wax impressions, valve tracings, and a brass gauge. The counterseal above Tovan's local mark can establish whether Vask's office authorized the transfer.",
      },
      {
        text: "A canalwright can compare the valve tracings with the order: the private mill branch was opened while the emergency spillway stayed shut. That would contradict an emergency diversion without requiring a witness.",
        when: [{ type: "flag", flag: "background-canalwright", value: true }],
      },
    ],
  },
  {
    id: "witness-cellar",
    title: "Witness Cellar",
    text: [
      {
        text: "Mara Venn sits beside a dead lantern with both hands around a brother's unpaid notice. She copied the order under threat and believes Vask can still reach her family.",
      },
      {
        text: "Mara recognizes the authority you gave the council. She will not put her name on an informal deposition for you. Offer a professional guarantee, protect her silence, or return to the hall for an official summons.",
        when: [{ type: "flag", flag: "council-control", value: true }],
      },
      {
        text: "Your field-medic training gives Mara a way to breathe through the questioning before she decides what she can say.",
        when: [{ type: "flag", flag: "background-field-medic", value: true }],
      },
      {
        text: "An oathkeeper's safe-conduct can bind the Archive to Mara's protection, even if Vask's clerks demand her name.",
        when: [{ type: "flag", flag: "background-oathkeeper", value: true }],
      },
    ],
  },
  {
    id: "lantern-hearing",
    title: "Lantern Hearing",
    text: [
      {
        text: "Sera Vale calls the hearing. Oren Vask arrives with a clean coat and an older seal, insisting that the stolen order was an emergency correction. Mara's testimony, if you took it, waits behind the screen.",
      },
      {
        text: "The shared channel's maintenance marks contradict Vask's correction.",
        when: [{ type: "flag", flag: "shared-water", value: true }],
      },
      {
        text: "The council ration list puts Vask's office behind every bucket Tovan released.",
        when: [{ type: "flag", flag: "council-control", value: true }],
      },
      {
        text: "Bram's family manifest records who paid for the diversion with a roof, a market, and a place to sleep.",
        when: [{ type: "flag", flag: "evacuation-plan", value: true }],
      },
      {
        text: "Mara's name can remain sealed while the case is published.",
        when: [{ type: "flag", flag: "archive-witness-protected", value: true }],
      },
      {
        text: "Your oathkeeper's writ is still open. Vask can be compelled to answer while Mara remains behind the screen.",
        when: [{ type: "flag", flag: "oathkeeper-obligation", value: true }],
      },
      {
        text: "Mara's testimony is signed, but no protection covers the name on the page.",
        when: [{ type: "flag", flag: "archive-witness-testimony", value: true }, { type: "flag", flag: "archive-witness-protected", value: false }],
      },
      {
        text: "Mara appeared under your council summons. She confirms the order but will not look at you; the summons has added another claim on your work.",
        when: [{ type: "flag", flag: "archive-witness-coerced", value: true }],
      },
      {
        text: "No witness has entered the record. The documents can still support a negotiated filing.",
        when: [{ type: "flag", flag: "archive-witness-testimony", value: false }],
      },
    ],
  },
  {
    id: "lowsail-reckoning",
    title: "Lowsail After the Lanterns",
    text: [
      {
        text: "The Archive's lantern notice reaches Lowsail before the next market bell. You have already closed the local account; now the town must live with what the record says.",
      },
      {
        text: "The notice certifies Nessa's shared repair and gives her a standing claim against another diversion.",
        when: [{ type: "flag", flag: "shared-water", value: true }, { type: "flag", flag: "archive-verdict-exposed", value: true }],
      },
      {
        text: "The notice puts council rationing under challenge. Tovan's guards still know where you sleep.",
        when: [{ type: "flag", flag: "council-control", value: true }, { type: "flag", flag: "archive-verdict-exposed", value: true }],
      },
      {
        text: "The notice enters Bram's family manifest as evidence of why the market was sacrificed.",
        when: [{ type: "flag", flag: "evacuation-plan", value: true }, { type: "flag", flag: "archive-verdict-exposed", value: true }],
      },
      {
        text: "Mara's name is on the public page. Vask is removed, but the witness now needs protection beyond the Archive's doors.",
        when: [{ type: "flag", flag: "archive-verdict-exposed", value: true }, { type: "flag", flag: "archive-witness-exposed", value: true }],
      },
      {
        text: "Vask is named without Mara. Sera seals the copyist's identity while the official answers for the order.",
        when: [{ type: "flag", flag: "archive-verdict-exposed", value: true }, { type: "flag", flag: "archive-witness-protected", value: true }],
      },
      {
        text: "Mara is safe, but Vask keeps his post and the order's authority remains available to anyone who wants it.",
        when: [{ type: "flag", flag: "archive-verdict-sealed", value: true }],
      },
      {
        text: "Sera files the documents as a negotiated record. No official is exposed, but the next investigator can find the trail.",
        when: [{ type: "flag", flag: "archive-verdict-negotiated", value: true }],
      },
      {
        text: "Mara's name is excluded from the Archive record; the documents carry the case.",
        when: [{ type: "flag", flag: "archive-witness-omitted", value: true }],
      },
      {
        text: "The field-medic mark is entered beside Mara's deposition. Your professional duty makes the protection a public promise.",
        when: [{ type: "flag", flag: "archive-field-medic-witness", value: true }],
      },
      {
        text: "Mara refuses to speak to you outside the record. The hearing used her account, but your summons made her brother's debt into another threat.",
        when: [{ type: "flag", flag: "archive-witness-coerced", value: true }],
      },
      {
        text: "The oathkeeper's writ is discharged in the notice; you made the official answer for the promise you bound.",
        when: [{ type: "flag", flag: "oathkeeper-vow-discharged", value: true }],
      },
    ],
  },
] as const satisfies readonly SceneData[];

export const LANTERN_CHOICES = [
  {
    id: "enter-lantern-hall",
    scene: "lantern-landing",
    label: "Enter the Archive hall",
    description: "Put the stolen order before Sera Vale and begin the investigation.",
    effects: [{ type: "goTo", scene: "archive-hall" }],
  },
  {
    id: "leave-lantern-landing",
    scene: "lantern-landing",
    label: "Leave the Archive",
    description: "Keep the order and leave the opened case before its investigation or hearing.",
    effects: [{ type: "addFact", fact: "archive-case-opened" }],
    outcome: { status: "departed", summary: "You leave the Lantern Archive before its hearing. The stolen order remains contested." },
  },
  {
    id: "inspect-diversion-ledger",
    scene: "archive-hall",
    label: "Inspect the diversion ledger",
    description: "Use the public stacks to find the night entry. Risk +1 while Vask's clerks watch the search.",
    when: [
      { type: "flag", flag: "archive-ledger-evidence", value: false },
      { type: "flag", flag: "archive-ledger-search-started", value: false },
    ],
    effects: [
      { type: "adjustResource", resource: "risk", delta: 1 },
      { type: "setFlag", flag: "archive-ledger-search-started", value: true },
      { type: "goTo", scene: "diversion-ledger-room" },
    ],
  },
  {
    id: "return-to-night-ledger",
    scene: "archive-hall",
    label: "Return to Jalen at the night ledger",
    description: "Return to the panel you found earlier and reconsider Jalen's amnesty. The search has already drawn attention; returning adds no risk.",
    when: [
      { type: "flag", flag: "archive-ledger-evidence", value: false },
      { type: "flag", flag: "archive-ledger-search-started", value: true },
    ],
    effects: [{ type: "goTo", scene: "diversion-ledger-room" }],
  },
  {
    id: "read-nessa-maintenance-log",
    scene: "archive-hall",
    label: "File Nessa's maintenance log",
    description: "Use the shared repair's maintenance trail to open the diversion ledger without adding risk.",
    when: [{ type: "flag", flag: "shared-water", value: true }, { type: "flag", flag: "archive-ledger-evidence", value: false }],
    effects: [
      { type: "setFlag", flag: "archive-ledger-evidence", value: true },
      { type: "adjustResource", resource: "archive-evidence", delta: 1 },
      { type: "addFact", fact: "archive-ledger-copied" },
      { type: "goTo", scene: "archive-hall" },
    ],
  },
  {
    id: "surrender-council-seal-for-ledger",
    scene: "archive-hall",
    label: "Open the official file with your council seal",
    description: "Give Sera access to the sealed ration file and its night ledger. She assumes one of your obligations for cooperating: debt -1. Keep the seal as your custody receipt.",
    when: [
      { type: "flag", flag: "council-control", value: true },
      { type: "flag", flag: "council-seal", value: true },
      { type: "flag", flag: "archive-ledger-evidence", value: false },
      { type: "resourceAtLeast", resource: "debt", value: 1 },
    ],
    effects: [
      { type: "adjustResource", resource: "debt", delta: -1 },
      { type: "setFlag", flag: "archive-ledger-evidence", value: true },
      { type: "adjustResource", resource: "archive-evidence", delta: 1 },
      { type: "addFact", fact: "archive-ledger-copied" },
      { type: "goTo", scene: "archive-hall" },
    ],
  },
  {
    id: "file-bram-family-manifest",
    scene: "archive-hall",
    label: "File Bram's family manifest",
    description: "File the families' losses to secure an emergency records request. Sera obtains the night ledger and adds the evacuation manifest to the case, without a public search or added risk.",
    when: [{ type: "flag", flag: "evacuation-plan", value: true }, { type: "flag", flag: "archive-ledger-evidence", value: false }],
    effects: [
      { type: "setFlag", flag: "archive-ledger-evidence", value: true },
      { type: "setFlag", flag: "archive-evacuation-docket", value: true },
      { type: "adjustResource", resource: "archive-evidence", delta: 1 },
      { type: "addFact", fact: "archive-ledger-copied" },
      { type: "goTo", scene: "archive-hall" },
    ],
  },
  {
    id: "trace-seal-chain",
    scene: "archive-hall",
    label: "Trace the seal chain",
    description: "Take the order to the seal workroom and compare the official impressions.",
    when: [{ type: "flag", flag: "archive-seal-evidence", value: false }],
    effects: [{ type: "goTo", scene: "seal-workroom" }],
  },
  {
    id: "speak-with-mara",
    scene: "archive-hall",
    label: "Seek Mara in the witness cellar",
    description: "Ask the copyist what she saw and decide whether the Archive can keep her safe.",
    when: [{ type: "flag", flag: "archive-witness-contacted", value: false }],
    effects: [{ type: "goTo", scene: "witness-cellar" }],
  },
  {
    id: "ask-nessa-to-vouch-for-mara",
    scene: "archive-hall",
    label: "Ask Nessa to vouch for Mara",
    description: "Nessa backs your request with the shared channel's repair log. Sera grants Mara and her brother protected lodging, and Mara signs a sealed deposition. No additional resource cost.",
    when: [{ type: "flag", flag: "shared-water", value: true }, { type: "flag", flag: "archive-witness-contacted", value: false }],
    effects: [
      { type: "setFlag", flag: "archive-witness-contacted", value: true },
      { type: "setFlag", flag: "archive-witness-testimony", value: true },
      { type: "setFlag", flag: "archive-witness-protected", value: true },
      { type: "adjustResource", resource: "archive-evidence", delta: 1 },
      { type: "addFact", fact: "archive-witness-heard" },
      { type: "addFact", fact: "archive-witness-protected" },
      { type: "goTo", scene: "archive-hall" },
    ],
  },
  {
    id: "use-council-debt-to-summon-mara",
    scene: "archive-hall",
    label: "Order a council summons for Mara",
    description: "Have Tovan compel Mara to testify by threatening collection of her brother's debt. You owe another council favor: debt +1. Her name receives no protection.",
    when: [
      { type: "flag", flag: "council-control", value: true },
      { type: "flag", flag: "archive-witness-contacted", value: false },
    ],
    effects: [
      { type: "adjustResource", resource: "debt", delta: 1 },
      { type: "setFlag", flag: "archive-witness-contacted", value: true },
      { type: "setFlag", flag: "archive-witness-testimony", value: true },
      { type: "setFlag", flag: "archive-witness-coerced", value: true },
      { type: "adjustResource", resource: "archive-evidence", delta: 1 },
      { type: "addFact", fact: "archive-witness-heard" },
      { type: "addFact", fact: "archive-witness-coerced" },
      { type: "goTo", scene: "archive-hall" },
    ],
  },
  {
    id: "shelter-mara-with-bram-manifest",
    scene: "archive-hall",
    label: "Shelter Mara with Bram's manifest",
    description: "Use the evacuation families' safe ground to hide Mara. She stays silent, so this adds no evidence.",
    when: [{ type: "flag", flag: "evacuation-plan", value: true }, { type: "flag", flag: "archive-witness-contacted", value: false }],
    effects: [
      { type: "setFlag", flag: "archive-witness-contacted", value: true },
      { type: "setFlag", flag: "archive-witness-protected", value: true },
      { type: "setFlag", flag: "archive-witness-silent", value: true },
      { type: "addFact", fact: "archive-witness-protected" },
      { type: "goTo", scene: "archive-hall" },
    ],
  },
  {
    id: "call-lantern-hearing",
    scene: "archive-hall",
    label: "Call the Lantern hearing",
    description: "Bring the gathered evidence before Sera Vale, Oren Vask, and the witness question.",
    when: [
      { type: "resourceAtLeast", resource: "archive-evidence", value: 2 },
      { type: "flag", flag: "archive-verdict-exposed", value: false },
      { type: "flag", flag: "archive-verdict-sealed", value: false },
      { type: "flag", flag: "archive-verdict-negotiated", value: false },
    ],
    effects: [{ type: "goTo", scene: "lantern-hearing" }],
  },
  {
    id: "leave-lantern-archive",
    scene: "archive-hall",
    label: "Leave the Archive",
    description: "End the investigation without asking the Archive to decide the case.",
    effects: [{ type: "addFact", fact: "archive-case-opened" }],
    outcome: { status: "departed", summary: "You leave the Lantern Archive with the order unresolved. Vask's claim survives the silence." },
  },
  {
    id: "secure-jalen-amnesty",
    scene: "diversion-ledger-room",
    label: "Secure Jalen's amnesty",
    description: "Promise the porter that the Archive will protect his testimony, then copy the night ledger.",
    when: [{ type: "flag", flag: "archive-ledger-evidence", value: false }],
    effects: [
      { type: "setFlag", flag: "archive-ledger-evidence", value: true },
      { type: "setFlag", flag: "archive-porter-amnesty", value: true },
      { type: "adjustResource", resource: "archive-evidence", delta: 1 },
      { type: "addFact", fact: "archive-ledger-copied" },
      { type: "addFact", fact: "archive-porter-amnesty" },
      { type: "goTo", scene: "archive-hall" },
    ],
  },
  {
    id: "leave-ledger-room",
    scene: "diversion-ledger-room",
    label: "Leave the night ledger",
    description: "Leave Jalen's panel closed and return to the Archive hall.",
    effects: [{ type: "goTo", scene: "archive-hall" }],
  },
  {
    id: "compare-seal-impressions",
    scene: "seal-workroom",
    label: "Compare the seal impressions",
    description: "Match the counterseal above Tovan's mark to Vask's office. This proves authorization, though Vask can still claim an emergency.",
    when: [{ type: "flag", flag: "archive-seal-evidence", value: false }],
    effects: [
      { type: "setFlag", flag: "archive-seal-evidence", value: true },
      { type: "adjustResource", resource: "archive-evidence", delta: 1 },
      { type: "addFact", fact: "archive-seal-chain-traced" },
      { type: "goTo", scene: "archive-hall" },
    ],
  },
  {
    id: "reconstruct-seal-pressure",
    scene: "seal-workroom",
    label: "Reconstruct the pressure mark",
    description: "Match Vask's counterseal and reconstruct the valve settings: his private mill branch opened while the emergency spillway stayed shut. With the ledger, this refutes his defense without Mara's testimony.",
    when: [{ type: "flag", flag: "background-canalwright", value: true }, { type: "flag", flag: "archive-seal-evidence", value: false }],
    effects: [
      { type: "setFlag", flag: "archive-seal-evidence", value: true },
      { type: "setFlag", flag: "archive-technical-proof", value: true },
      { type: "adjustResource", resource: "archive-evidence", delta: 1 },
      { type: "addFact", fact: "archive-seal-chain-traced" },
      { type: "addFact", fact: "archive-technical-proof" },
      { type: "goTo", scene: "archive-hall" },
    ],
  },
  {
    id: "leave-seal-workroom",
    scene: "seal-workroom",
    label: "Leave the seal bench",
    description: "Return to the Archive hall without committing the seal comparison.",
    effects: [{ type: "goTo", scene: "archive-hall" }],
  },
  {
    id: "record-mara-testimony",
    scene: "witness-cellar",
    label: "Record Mara's testimony",
    description: "Mara agrees to state that Vask ordered water reserved for his mill and threatened her brother over the copy. Her signed account has no protection; the hearing will decide whether to publish or seal it.",
    when: [{ type: "flag", flag: "archive-witness-contacted", value: false }, { type: "flag", flag: "council-control", value: false }],
    effects: [
      { type: "setFlag", flag: "archive-witness-contacted", value: true },
      { type: "setFlag", flag: "archive-witness-testimony", value: true },
      { type: "adjustResource", resource: "archive-evidence", delta: 1 },
      { type: "addFact", fact: "archive-witness-heard" },
      { type: "goTo", scene: "archive-hall" },
    ],
  },
  {
    id: "stabilize-mara-before-deposition",
    scene: "witness-cellar",
    label: "Stabilize Mara before the deposition",
    description: "Use field-medic practice to steady Mara and secure protected testimony without spending medicine. Risk +1 while you sign the professional deposition.",
    when: [{ type: "flag", flag: "background-field-medic", value: true }, { type: "flag", flag: "archive-witness-contacted", value: false }],
    effects: [
      { type: "setFlag", flag: "archive-witness-contacted", value: true },
      { type: "setFlag", flag: "archive-witness-testimony", value: true },
      { type: "setFlag", flag: "archive-witness-protected", value: true },
      { type: "setFlag", flag: "archive-field-medic-witness", value: true },
      { type: "setFlag", flag: "field-medic-duty", value: true },
      { type: "adjustResource", resource: "risk", delta: 1 },
      { type: "adjustResource", resource: "archive-evidence", delta: 1 },
      { type: "addFact", fact: "archive-witness-heard" },
      { type: "addFact", fact: "archive-witness-protected" },
      { type: "addFact", fact: "field-medic-duty" },
      { type: "goTo", scene: "archive-hall" },
    ],
  },
  {
    id: "swear-mara-safe-conduct",
    scene: "witness-cellar",
    label: "Swear Mara safe conduct",
    description: "Bind the Archive to Mara's protection before she names the office that coerced her.",
    when: [{ type: "flag", flag: "background-oathkeeper", value: true }, { type: "flag", flag: "archive-witness-contacted", value: false }],
    effects: [
      { type: "setFlag", flag: "archive-witness-contacted", value: true },
      { type: "setFlag", flag: "archive-witness-testimony", value: true },
      { type: "setFlag", flag: "archive-witness-protected", value: true },
      { type: "setFlag", flag: "archive-oath-witness", value: true },
      { type: "setFlag", flag: "oathkeeper-obligation", value: true },
      { type: "adjustResource", resource: "archive-evidence", delta: 1 },
      { type: "addFact", fact: "archive-witness-heard" },
      { type: "addFact", fact: "archive-witness-protected" },
      { type: "addFact", fact: "archive-safe-conduct-bound" },
      { type: "goTo", scene: "archive-hall" },
    ],
  },
  {
    id: "keep-mara-hidden",
    scene: "witness-cellar",
    label: "Keep Mara hidden",
    description: "Move Mara to shelter without taking a deposition. She stays safe and silent; the case gains no evidence.",
    when: [{ type: "flag", flag: "archive-witness-contacted", value: false }],
    effects: [
      { type: "setFlag", flag: "archive-witness-contacted", value: true },
      { type: "setFlag", flag: "archive-witness-silent", value: true },
      { type: "setFlag", flag: "archive-witness-protected", value: true },
      { type: "addFact", fact: "archive-witness-protected" },
      { type: "goTo", scene: "archive-hall" },
    ],
  },
  {
    id: "leave-witness-cellar",
    scene: "witness-cellar",
    label: "Leave the witness cellar",
    description: "Leave Mara's decision for another visit and return to the hall.",
    effects: [{ type: "goTo", scene: "archive-hall" }],
  },
  {
    id: "publish-vask-and-name-mara",
    scene: "lantern-hearing",
    label: "Publish Vask's order and name Mara",
    description: "Expose the official with Mara's signed testimony. Vask falls, but the witness's name enters the public record; risk +1.",
    when: [
      { type: "resourceAtLeast", resource: "archive-evidence", value: 2 },
      { type: "flag", flag: "archive-ledger-evidence", value: true },
      { type: "flag", flag: "archive-seal-evidence", value: true },
      { type: "flag", flag: "archive-witness-testimony", value: true },
      { type: "flag", flag: "archive-witness-protected", value: false },
    ],
    effects: [
      { type: "setFlag", flag: "archive-verdict-exposed", value: true },
      { type: "setFlag", flag: "archive-witness-exposed", value: true },
      { type: "adjustResource", resource: "risk", delta: 1 },
      { type: "addFact", fact: "archive-vask-exposed" },
      { type: "addFact", fact: "archive-witness-exposed" },
      { type: "goTo", scene: "lowsail-reckoning" },
    ],
  },
  {
    id: "publish-vask-anonymously",
    scene: "lantern-hearing",
    label: "Publish Vask's order anonymously",
    description: "Expose the official while Sera seals Mara's name behind the Archive's protection.",
    when: [
      { type: "resourceAtLeast", resource: "archive-evidence", value: 2 },
      { type: "flag", flag: "archive-ledger-evidence", value: true },
      { type: "flag", flag: "archive-seal-evidence", value: true },
      { type: "flag", flag: "archive-witness-testimony", value: true },
      { type: "flag", flag: "archive-witness-protected", value: true },
    ],
    effects: [
      { type: "setFlag", flag: "archive-verdict-exposed", value: true },
      { type: "addFact", fact: "archive-vask-exposed" },
      { type: "addFact", fact: "archive-witness-protected" },
      { type: "goTo", scene: "lowsail-reckoning" },
    ],
  },
  {
    id: "publish-technical-record",
    scene: "lantern-hearing",
    label: "Publish the technical record",
    description: "Use a canalwright's pressure proof and the two documents to expose Vask without putting Mara in the case.",
    when: [
      { type: "resourceAtLeast", resource: "archive-evidence", value: 2 },
      { type: "flag", flag: "archive-ledger-evidence", value: true },
      { type: "flag", flag: "archive-seal-evidence", value: true },
      { type: "flag", flag: "archive-technical-proof", value: true },
    ],
    effects: [
      { type: "setFlag", flag: "archive-verdict-exposed", value: true },
      { type: "setFlag", flag: "archive-witness-omitted", value: true },
      { type: "addFact", fact: "archive-vask-exposed" },
      { type: "addFact", fact: "archive-witness-omitted" },
      { type: "goTo", scene: "lowsail-reckoning" },
    ],
  },
  {
    id: "compel-vask-under-oath",
    scene: "lantern-hearing",
    label: "Compel Vask under oath",
    description: "Use the safe-conduct oath to make Vask answer while Mara remains protected.",
    when: [
      { type: "resourceAtLeast", resource: "archive-evidence", value: 2 },
      { type: "flag", flag: "archive-ledger-evidence", value: true },
      { type: "flag", flag: "archive-seal-evidence", value: true },
      { type: "flag", flag: "archive-oath-witness", value: true },
      { type: "flag", flag: "oathkeeper-obligation", value: true },
    ],
    effects: [
      { type: "setFlag", flag: "archive-verdict-exposed", value: true },
      { type: "setFlag", flag: "archive-witness-protected", value: true },
      { type: "setFlag", flag: "oathkeeper-obligation", value: false },
      { type: "setFlag", flag: "oathkeeper-vow-discharged", value: true },
      { type: "addFact", fact: "archive-vask-exposed" },
      { type: "addFact", fact: "archive-witness-protected" },
      { type: "addFact", fact: "oathkeeper-vow-discharged" },
      { type: "goTo", scene: "lowsail-reckoning" },
    ],
  },
  {
    id: "seal-mara-testimony",
    scene: "lantern-hearing",
    label: "Seal Mara's testimony",
    description: "Protect Mara by sealing her testimony. Vask keeps his post and the order's authority remains available.",
    when: [
      { type: "resourceAtLeast", resource: "archive-evidence", value: 2 },
      { type: "flag", flag: "archive-witness-testimony", value: true },
    ],
    effects: [
      { type: "setFlag", flag: "archive-verdict-sealed", value: true },
      { type: "setFlag", flag: "archive-witness-protected", value: true },
      { type: "addFact", fact: "archive-case-sealed" },
      { type: "addFact", fact: "archive-witness-protected" },
      { type: "goTo", scene: "lowsail-reckoning" },
    ],
  },
  {
    id: "negotiate-provisional-record",
    scene: "lantern-hearing",
    label: "Negotiate a provisional record",
    description: "File the ledger and seal as a protected lead. Do not expose Vask or ask Mara to testify today.",
    when: [
      { type: "resourceAtLeast", resource: "archive-evidence", value: 2 },
      { type: "flag", flag: "archive-ledger-evidence", value: true },
      { type: "flag", flag: "archive-seal-evidence", value: true },
      { type: "flag", flag: "archive-witness-testimony", value: false },
    ],
    effects: [
      { type: "setFlag", flag: "archive-verdict-negotiated", value: true },
      { type: "setFlag", flag: "archive-witness-omitted", value: true },
      { type: "addFact", fact: "archive-record-negotiated" },
      { type: "addFact", fact: "archive-witness-omitted" },
      { type: "goTo", scene: "lowsail-reckoning" },
    ],
  },
  {
    id: "adjourn-hearing-for-witness",
    scene: "lantern-hearing",
    label: "Adjourn and seek the witness",
    description: "Pause the hearing before a verdict and return to the Archive hall for Mara's account.",
    when: [
      { type: "resourceAtLeast", resource: "archive-evidence", value: 2 },
      { type: "flag", flag: "archive-witness-contacted", value: false },
      { type: "flag", flag: "archive-hearing-adjourned", value: false },
    ],
    effects: [
      { type: "setFlag", flag: "archive-hearing-adjourned", value: true },
      { type: "addFact", fact: "archive-hearing-adjourned" },
      { type: "goTo", scene: "archive-hall" },
    ],
  },
  {
    id: "leave-hearing-undecided",
    scene: "lantern-hearing",
    label: "Leave the hearing undecided",
    description: "Walk away before the Archive records a verdict.",
    effects: [{ type: "addFact", fact: "archive-case-opened" }],
    outcome: { status: "departed", summary: "You leave the Lantern hearing undecided. Vask's office keeps its clean record for now." },
  },
  {
    id: "close-archive-case",
    scene: "lowsail-reckoning",
    label: "Close the Archive case",
    description: "Accept the Lantern record and let Lowsail live with the evidence, protection, and risk you chose.",
    effects: [
      { type: "setFlag", flag: "archive-returned", value: true },
      { type: "addFact", fact: "archive-case-closed" },
    ],
    outcome: { status: "completed", summary: "You close the Lantern Archive case after carrying its verdict back to Lowsail. The order, the witness, and the town's water now share one record." },
  },
  {
    id: "leave-lowsail-reckoning",
    scene: "lowsail-reckoning",
    label: "Leave Lowsail with the record open",
    description: "Leave the town before accepting the Archive's final account.",
    effects: [{ type: "addFact", fact: "archive-case-opened" }],
    outcome: { status: "departed", summary: "You leave Lowsail with the Lantern record open. The town keeps the consequences without your final answer." },
  },
] as const satisfies readonly ChoiceData[];
